export const SELECT_VALUE = 'SELECT_VALUE';
export const CHANGE_RECORD_LOCATION = 'CHANGE_RECORD_LOCATION';
export const CHANGE_RECORD_TAGS = 'CHANGE_RECORD_TAGS';
export const SAVE_RECORD = 'SAVE_RECORD';
export const SET_LOADED_TAGS = 'SET_LOADED_TAGS';
export const ADD_TAG_OPTION = 'ADD_TAG_OPTION';
